title: Kokuhagen
description: Aventuras en Copenhague
url: "https://kokuhagen.com" 
twitter:
  username: kokuma
  card: summary
social:
  name: Juan Alonso
  links:
    - https://twitter.com/kokuma
lang: es

baseurl: "" 
future: false

twitter_username: kokuma
show_excerpts: true
google_analytics: UA-125783247-2

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%d/%m/%y"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
